### ISSUE TITLE
Use twox64_concat to map address to balance

### ISSUE THREAD

**Issue by shawntabrizi** [apopiak/pallet-stablecoin#3]
https://github.com/apopiak/pallet-stablecoin/blob/e4074e6753fdc9257922826a7a1218735d25e030/src/lib.rs#L191

See https://github.com/paritytech/substrate/issues/4917

**Comment by apopiak** [comment]
Thanks for the info! Users can transfer arbitrary amounts of stablecoins to any valid `AccountId`, though, so I wonder whether `blake2_128_concat` might be the better option?

**Comment by shawntabrizi** [comment]
Yes you are right!

**Comment by apopiak** [comment]
addressed in `431608a59afd9cfcca1f2684efe1d1b13fcf438d`
