### ISSUE TITLE
Not allowed to panic! in the runtime

### ISSUE THREAD

**Issue by shawntabrizi** [apopiak/pallet-stablecoin#7]
https://github.com/apopiak/pallet-stablecoin/blob/e4074e6753fdc9257922826a7a1218735d25e030/src/lib.rs#L591

If you allow the runtime to panic!, you will allow an attacker to submit an extrinsic which causes a panic. This means that they can cause a node to execute some code, it will panic, and the entire transaction will not be processed, including the fees. This means it is an spam/dos attack vector.

**Comment by apopiak** [comment]
This is a `debug_assert` with the assumption that noone will run a debug build in production. Will not trigger in production.
